### ISSUE TITLE
Content that does not fit your screen horizontally isn't shown

### ISSUE THREAD

**Issue by lotrien** [xsnippet/xsnippet-web#136]
Content of a snippet that does not fit your screen horizontally can be scrolled yet cannot be seen. It looks like that internally the editor does understand that there's a content to show, yet when you scroll nothing is shown.

Steps to reproduce:

1. Open this snippet in your web browser https://xsnippet.org/364076
2. Click on the snippet content and scroll horizontally.
3. Note that only part of the content is shown. You can find the whole content here: https://xsnippet.org/364076/raw

**Comment by abhayjatindoshi** [comment]
I found out the css issue. But i'm unable to locate the editor component in your react code base. Could you help me out ? 
I've just recently started familiarizing with reactJS.

**Comment by frankwaldal** [comment]
> I found out the css issue. But i'm unable to locate the editor component in your react code base. Could you help me out ?
> I've just recently started familiarizing with reactJS.

I would guess `/src/styles/snippets.styl` would be the correct file. Just from a quick lookthrough

**Comment by lotrien** [comment]
> I found out the css issue. But i'm unable to locate the editor component in your react code base. Could you help me out ?
Hey, component which contains editor is https://github.com/xsnippet/xsnippet-web/blob/master/src/components/Snippet.jsx (you can find `<AceEditor />` component within this file).

**Comment by abhayjatindoshi** [comment]
Thanks :) . I didn't realise that you were using _Stylus_. Really happy to see an app using all the new technologies possible. 

The problem was because of an override css in `src/styles/common/overwrite.styl`

I've removed that override and tested. Also setting up the build was as easy as `npm install && npm start` and it started to work with the data from the live server. 

I see tremendous effort that you guys have made in-order to maintain and continuously keep all the components updated. Hats off. 

I've created a PR #137 But it seems it requires some more of me. Please let me know if I have to do anything more ..
